version: '3'
services:
    minio:
        build:
            context: ./
            dockerfile: ./images/minio/Dockerfile
        container_name: minio
        restart: always
        volumes:
            - ./data:/home/pi/data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command: minio server --address :9000 --console-address :9001 data/
    postgres:
        image: "postgres"
        restart: "always"
        container_name: "postgres"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_AIRFLOW_PASS}
            - POSTGRES_USER=${POSTGRES_AIRFLOW_USER}
            - POSTGRES_DB=${POSTGRES_AIRFLOW_DB}
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    airflow-scheduler:
        build:
            context: ./
            dockerfile: ./images/airflow-master/Dockerfile
        depends_on:
            - "postgres"
        container_name: airflow-scheduler
        restart: always
        extra_hosts:
            host.docker.internal: host-gateway
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/usr/local/airflow/plugins
        #            - ./certs:/opt/airflow/certs
            - ./airflow.cfg:/opt/airflow/airflow.cfg
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASS}@${POSTGRES_AIRFLOW_HOST}:${POSTGRES_AIRFLOW_PORT}/${POSTGRES_AIRFLOW_DB}
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://${POSTGRES_AIRFLOW_RESULTS_USER}:${POSTGRES_AIRFLOW_RESULTS_PASS}@${POSTGRES_AIRFLOW_RESULTS_HOST}:${POSTGRES_AIRFLOW_RESULTS_PORT}/${POSTGRES_AIRFLOW_RESULTS_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
        command: airflow scheduler
        
    airflow-webserver:
        build:
            context: ./
            dockerfile: ./images/airflow-master/Dockerfile
        depends_on:
            - "postgres"
        container_name: airflow-webserver
        restart: always
        extra_hosts:
            host.docker.internal: host-gateway
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/usr/local/airflow/plugins
        #            - ./certs:/opt/airflow/certs
            - ./airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "8000:8000"
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASS}@${POSTGRES_AIRFLOW_HOST}:${POSTGRES_AIRFLOW_PORT}/${POSTGRES_AIRFLOW_DB}
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://${POSTGRES_AIRFLOW_RESULTS_USER}:${POSTGRES_AIRFLOW_RESULTS_PASS}@${POSTGRES_AIRFLOW_RESULTS_HOST}:${POSTGRES_AIRFLOW_RESULTS_PORT}/${POSTGRES_AIRFLOW_RESULTS_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
        command: airflow webserver --port 8000
